In [3]:
import numpy as np
a=np.array([1,2,2])
print('1D array')
print(a)
print()

1D array
[1 2 2]



In [2]:
b=np.array([(3,4,5),(2,3,4)])
print('2D array: ')
print(b)

2D array: 
[[3 4 5]
 [2 3 4]]


In [4]:
c=np.array([(1,2,3,4),(3,4,5,0),(6,7,8,0),(9,10,11,11)])
print(c)


[[ 1  2  3  4]
 [ 3  4  5  0]
 [ 6  7  8  0]
 [ 9 10 11 11]]
