In [1]:
import numpy as np
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [2]:
matriz1 = np.arange(2,10)

In [3]:
matriz1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
mat2= np.arange(2,10).reshape(4,2)

In [6]:
mat2

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
mat2-9

array([[-7, -6],
       [-5, -4],
       [-3, -2],
       [-1,  0]])

In [9]:
import pandas as pd


In [10]:
# Create dictionary of test scores
test_dict = {'Pedro':[10, 9, 8.5], 'María': [2, 9, 9], 'Jorge':[10, 10, 10]}

In [11]:
# Create DataFrame
df = pd.DataFrame(test_dict)

In [12]:
# Display DataFrame
df

Pedro  María  Jorge
0   10.0      2     10
1    9.0      9     10
2    8.5      9     10

In [13]:
# Transpose DataFrame
df=df.T

In [14]:
df

0     1     2
Pedro  10.0   9.0   8.5
María   2.0   9.0   9.0
Jorge  10.0  10.0  10.0